import { createSlice } from '@reduxjs/toolkit';

export const skillsSlice = createSlice({
    name: 'skills',
    initialState: {
        skills: [
            {
                name: 'HTML',
                id: 'skill1',
                fullName: 'Hyper Text Markup Language',
                icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-plain.svg',
                tags: ['frontend', 'design'],
                level: 9,
                link: 'https://developer.mozilla.org/en-US/docs/Web/HTML',
            },
            {
                name: 'CSS',
                id: 'skill2',
                fullName: 'Cascading Style Sheets',
                icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-plain.svg',
                tags: ['frontend', 'design'],
                level: 8,
                link: 'https://developer.mozilla.org/en-US/docs/Web/CSS',
            },
            {
                name: 'JavaScript',
                id: 'skill3',
                fullName: 'JavaScript',
                icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-plain.svg',
                tags: ['frontend', 'interactivity'],
                level: 7,
                link: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
            },
            {
                name: 'React',
                id: 'skill4',
                fullName: 'React',
                icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg',
                tags: ['frontend', 'design', 'interactivity'],
                level: 8,
                link: 'https://reactjs.org/',
            },
            {
                name: 'Redux',
                id: 'skill5',
                fullName: 'Redux',
                icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redux/redux-original.svg',
                tags: ['frontend', 'design', 'backend', 'interactivity'],
                level: 8,
                link: 'https://redux.js.org/',
            },
            {
                name: 'PHP',
                id: 'skill6',
                fullName: 'Hypertext Preprocessor',
                icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/php/php-plain.svg',
                tags: ['frontend', 'design', 'backend', 'interactivity'],
                level: 7,
                link: 'https://www.php.net/',
            },
            {
                name: 'Git',
                id: 'skill7',
                fullName: 'Git',
                icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg',
                tags: ['development'],
                level: 6,
                link: 'https://git-scm.com/',
            },
            {
                name: 'GitHub',
                id: 'skill8',
                fullName: 'GitHub',
                icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg',
                tags: ['development'],
                level: 6,
                link: 'https://github.com/',
            },
            {
                name: 'WordPress',
                id: 'skill9',
                fullName: 'WordPress.org',
                icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/wordpress/wordpress-plain.svg',
                tags: ['frontend', 'design', 'backend', 'cms', 'interactivity'],
                level: 8,
                link: 'https://wordpress.org/',
            },
            {
                name: 'Sass',
                id: 'skill10',
                fullName: 'Sass',
                icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sass/sass-original.svg',
                tags: ['frontend', 'design'],
                level: 7,
                link: 'https://sass-lang.com/',
            },
            {
                name: 'Frontity',
                id: 'skill11',
                fullName: 'Frontity',
                icon: 'https://frontity.org/wp-content/uploads/2020/04/FrontityBlueLogo.svg',
                tags: ['frontend', 'design', 'backend', 'cms', 'interactivity'],
                level: 6,
                link: 'https://frontity.org/',
            },
            {
                name: 'Bash',
                id: 'skill12',
                fullName: 'Bash',
                icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bash/bash-original.svg',
                tags: ['development', 'backend'],
                level: 8,
                link: 'https://www.gnu.org/software/bash/',
            },
            {
                name: 'Node.js',
                id: 'skill13',
                fullName: 'Node.js',
                icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg',
                tags: ['development', 'backend'],
                level: 3,
                link: 'https://nodejs.org/en/',
            },
            {
                name: 'Mocha',
                id: 'skill14',
                fullName: 'Mocha',
                icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mocha/mocha-plain.svg',
                tags: ['development'],
                level: 5,
                link: 'https://mochajs.org/',
            },
            {
                name: 'Jest',
                id: 'skill15',
                fullName: 'Jest',
                icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jest/jest-plain.svg',
                tags: ['development'],
                level: 5,
                link: 'https://jestjs.io/',
            },
        ],
    },
    reducers: {
        
    }
});

export const selectSkills = (state) => state.skills;
export default skillsSlice.reducer;